# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    container_name: hotelboard_backend

    env_file:
      - .env.development

    depends_on:
      - db
      - redis

    ports:
      - "8000:8000"

    restart: unless-stopped

  db:
    image: postgres:17

    env_file:
      - .env.development

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotelboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile

    container_name: hotelboard_frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped

  redis:
    image: redis:8-alpine

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    env_file:
      - .env.development

    depends_on:
      - db
      - redis

    command: celery -A config worker --loglevel=info

    restart: unless-stopped

  beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    env_file:
      - .env.development

    depends_on:
      - db
      - redis

    command: >
      celery -A config beat
      --loglevel=info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
