# Generated by Django 6.0.7 on 2026-07-18 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housekeepingrequest',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
