# Generated by Django 6.0.7 on 2026-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('HOUSEKEEPING', 'Housekeeping'), ('ENGINEERING', 'Engineering'), ('ROOM_SERVICE', 'Room Service')], default='HOUSEKEEPING', max_length=30),
        ),
    ]
